name: CD

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci --legacy-peer-deps

            - name: Build Next.js App
              run: npm run build

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN}}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build & Push image to Docker Hub
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/seenit:latest
                  build-args: |
                      TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Deploy from Docker Hub to Cloud Run
              uses: google-github-actions/deploy-cloudrun@v2
              with:
                  service: seenit
                  image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/seenit:latest
                  region: ${{ secrets.GCP_REGION }}
                  project_id: ${{ secrets.GCP_PROJECT_ID }}
                  env_vars: TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}